import { v4 as uuidv4 } from "uuid";

export const tweetsData = [
  {
    handle: "@Zack",
    profilePic: "images/zack.jpg",
    likes: 1,
    retweets: 0,
    tweetText:
      "Bro, I found a box full of premium treats behind the big tree at the park! First one there gets them all! 🦴🔥",
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Tanggol",
    profilePic: "images/tanggol.jpg",
    likes: 3,
    retweets: 2,
    tweetText:
      "I need volunteers for a one-way mission to hunt for food in the wild 🍗🌲. No experience necessary 🐾",
    replies: [
      {
        handle: "@Pandaman ✅",
        profilePic: "images/pandaman.jpg",
        tweetText: "Yes! Sign me up! 😎🛩",
        uuid: uuidv4(),
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Zack",
    profilePic: "images/zack.jpg",
    likes: 0,
    retweets: 0,
    tweetText: "How to use a camera?",
    tweetImage: "images/zackSelfie.jpg",
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Ringgo",
    profilePic: "images/ringgo.jpg",
    likes: 3,
    retweets: 3,
    tweetText: "Are you a hunter if you only kill a cockroach?",
    replies: [
      {
        handle: "@Dexter",
        profilePic: "images/dexter.jpg",
        tweetText: "No. Obviously not. Go get a job in McDonald's.",
        uuid: uuidv4(),
      },
      {
        handle: "@Toga",
        profilePic: "images/toga.jpg",
        tweetText: "You are wonderful just as you are! ❤️",
        uuid: uuidv4(),
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Polka",
    profilePic: "images/polka.jpg",
    likes: 2200,
    retweets: 1230,
    tweetText: "Who wants to share a bowl of cream tonight? 😽💕",
    replies: [
      {
        handle: "@Dexter",
        profilePic: "images/dexter.jpg",
        tweetText: "Only if you promise extra cuddles after! 😻🥛",
        uuid: uuidv4(),
      },
      {
        handle: "@Pandaman ✅",
        profilePic: "images/pandaman.jpg",
        tweetText: "@Dexter I saw your scandal 😝",
        tweetImage: "images/eut.jpg",
        uuid: uuidv4(),
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Tanggol",
    profilePic: "images/tanggol.jpg",
    likes: 6,
    retweets: 4,
    tweetText: "Rate my outfit! 🐾",
    tweetImage: "images/tanggolOutfit.jpg",
    replies: [
      {
        handle: "@Pandaman ✅",
        profilePic: "images/pandaman.jpg",
        tweetText: "2",
        uuid: uuidv4(),
      },
      {
        handle: "@Toga",
        profilePic: "images/toga.jpg",
        tweetText: "cute 😍",
        uuid: uuidv4(),
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
  {
    handle: "@Tigger",
    profilePic: "images/tigger.jpg",
    likes: 10,
    retweets: 3,
    tweetText: "If you don't see me in few days I'm dead already",
    replies: [
      {
        handle: "@Dexter",
        profilePic: "images/dexter.jpg",
        tweetText: "attention seeker",
        uuid: uuidv4(),
      },
      {
        handle: "@Toga",
        profilePic: "images/toga.jpg",
        tweetText: "don't give up",
        tweetImage: "images/hugs.gif",
        uuid: uuidv4(),
      },
      {
        handle: "@Zack",
        profilePic: "images/zack.jpg",
        tweetText: "nahhh",
        uuid: uuidv4(),
      },
      {
        handle: "@Tanggol",
        profilePic: "images/tanggol.jpg",
        tweetText: "where are you?",
        uuid: uuidv4(),
      },
      {
        handle: "@Pandaman",
        profilePic: "images/pandaman.jpg",
        tweetText: "",
        tweetImage: "images/coffin.gif",
        uuid: uuidv4(),
      },
      {
        handle: "@Ringgo",
        profilePic: "images/ringgo.jpg",
        tweetText: "RIP",
        uuid: uuidv4(),
      },
      {
        handle: "@Polka",
        profilePic: "images/polka.jpg",
        tweetText: ``,
        tweetImage: `images/pink.gif`,
        uuid: uuidv4(),
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: uuidv4(),
  },
];
